// Generated from: http://web.archive.org/web/20210303185939/https://www.computerhope.com/htmcolor.htm
#macro c_night                          #0c090a
#macro c_gunmetal                       #2c3539
#macro c_midnight                       #2b1b17
#macro c_charcoal                       #34282c
#macro c_dark_slate_grey                #25383c
#macro c_oil                            #3b3131
#macro c_black_cat                      #413839
#macro c_iridium                        #3d3c3a
#macro c_black_eel                      #463e3f
#macro c_black_cow                      #4c4646
#macro c_gray_wolf                      #504a4b
#macro c_vampire_gray                   #565051
#macro c_gray_dolphin                   #5c5858
#macro c_carbon_gray                    #625d5d
#macro c_ash_gray                       #666362
#macro c_cloudy_gray                    #6d6968
#macro c_smokey_gray                    #726e6d
#macro c_granite                        #837e7c
#macro c_battleship_gray                #848482
#macro c_gray_cloud                     #b6b6b4
#macro c_gray_goose                     #d1d0ce
#macro c_platinum                       #e5e4e2
#macro c_metallic_silver                #bcc6cc
#macro c_blue_gray                      #98afc7
#macro c_light_slate_gray               #6d7b8d
#macro c_slate_gray                     #657383
#macro c_jet_gray                       #616d7e
#macro c_mist_blue                      #646d7e
#macro c_marble_blue                    #566d7e
#macro c_slate_blue                     #737ca1
#macro c_steel_blue                     #4863a0
#macro c_blue_jay                       #2b547e
#macro c_dark_slate_blue                #2b3856
#macro c_midnight_blue                  #151b54
#macro c_navy_blue                      #000080
#macro c_blue_whale                     #342d7e
#macro c_lapis_blue                     #15317e
#macro c_denim_dark_blue                #151b8d
#macro c_earth_blue                     #0000a0
#macro c_cobalt_blue                    #0020c2
#macro c_blueberry_blue                 #0041c2
#macro c_sapphire_blue                  #2554c7
#macro c_blue_eyes                      #1569c7
#macro c_royal_blue                     #2b60de
#macro c_blue_orchid                    #1f45fc
#macro c_blue_lotus                     #6960ec
#macro c_light_slate_blue               #736aff
#macro c_windows_blue                   #357ec7
#macro c_glacial_blue_ice               #368bc1
#macro c_silk_blue                      #488ac7
#macro c_blue_ivy                       #3090c7
#macro c_blue_koi                       #659ec7
#macro c_columbia_blue                  #87afc7
#macro c_baby_blue                      #95b9c7
#macro c_light_steel_blue               #728fce
#macro c_ocean_blue                     #2b65ec
#macro c_blue_ribbon                    #306eff
#macro c_blue_dress                     #157dec
#macro c_dodger_blue                    #1589ff
#macro c_cornflower_blue                #6495ed
#macro c_sky_blue                       #6698ff
#macro c_butterfly_blue                 #38acec
#macro c_iceberg                        #56a5ec
#macro c_crystal_blue                   #5cb3ff
#macro c_deep_sky_blue                  #3bb9ff
#macro c_denim_blue                     #79baec
#macro c_light_sky_blue                 #82cafa
#macro c_day_sky_blue                   #82caff
#macro c_jeans_blue                     #a0cfec
#macro c_blue_angel                     #b7ceec
#macro c_pastel_blue                    #b4cfec
#macro c_sea_blue                       #c2dfff
#macro c_powder_blue                    #c6deff
#macro c_coral_blue                     #afdcec
#macro c_light_blue                     #addfff
#macro c_robin_egg_blue                 #bdedff
#macro c_pale_blue_lily                 #cfecec
#macro c_light_cyan                     #e0ffff
#macro c_water                          #ebf4fa
#macro c_aliceblue                      #f0f8ff
#macro c_azure                          #f0ffff
#macro c_light_slate                    #ccffff
#macro c_light_aquamarine               #93ffe8
#macro c_electric_blue                  #9afeff
#macro c_aquamarine                     #7fffd4
#macro c_cyan_or_aqua                   #00ffff
#macro c_tron_blue                      #7dfdfe
#macro c_blue_zircon                    #57feff
#macro c_blue_lagoon                    #8eebec
#macro c_celeste                        #50ebec
#macro c_blue_diamond                   #4ee2ec
#macro c_tiffany_blue                   #81d8d0
#macro c_cyan_opaque                    #92c7c7
#macro c_blue_hosta                     #77bfc7
#macro c_northern_lights_blue           #78c7c7
#macro c_medium_turquoise               #48cccd
#macro c_turquoise                      #43c6db
#macro c_jellyfish                      #46c7c7
#macro c_blue_green                     #7bccb5
#macro c_macaw_blue_green               #43bfc7
#macro c_light_sea_green                #3ea99f
#macro c_dark_turquoise                 #3b9c9c
#macro c_sea_turtle_green               #438d80
#macro c_medium_aquamarine              #348781
#macro c_greenish_blue                  #307d7e
#macro c_grayish_turquoise              #5e7d7e
#macro c_beetle_green                   #4c787e
#macro c_sea_green                      #4e8975
#macro c_camouflage_green               #78866b
#macro c_sage_green                     #848b79
#macro c_hazel_green                    #617c58
#macro c_venom_green                    #728c00
#macro c_fern_green                     #667c26
#macro c_dark_forest_green              #254117
#macro c_medium_sea_green               #306754
#macro c_medium_forest_green            #347235
#macro c_seaweed_green                  #437c17
#macro c_pine_green                     #387c44
#macro c_jungle_green                   #347c2c
#macro c_shamrock_green                 #347c17
#macro c_medium_spring_green            #348017
#macro c_forest_green                   #4e9258
#macro c_green_onion                    #6aa121
#macro c_spring_green                   #4aa02c
#macro c_lime_green                     #41a317
#macro c_clover_green                   #3ea055
#macro c_green_snake                    #6cbb3c
#macro c_alien_green                    #6cc417
#macro c_green_apple                    #4cc417
#macro c_yellow_green                   #52d017
#macro c_kelly_green                    #4cc552
#macro c_zombie_green                   #54c571
#macro c_frog_green                     #99c68e
#macro c_green_peas                     #89c35c
#macro c_dollar_bill_green              #85bb65
#macro c_dark_sea_green                 #8bb381
#macro c_iguana_green                   #9cb071
#macro c_avocado_green                  #b2c248
#macro c_pistachio_green                #9dc209
#macro c_salad_green                    #a1c935
#macro c_hummingbird_green              #7fe817
#macro c_nebula_green                   #59e817
#macro c_stoplight_go_green             #57e964
#macro c_algae_green                    #64e986
#macro c_jade_green                     #5efb6e
#macro c_emerald_green                  #5ffb17
#macro c_lawn_green                     #87f717
#macro c_chartreuse                     #8afb17
#macro c_dragon_green                   #6afb92
#macro c_mint_green                     #98ff98
#macro c_green_thumb                    #b5eaaa
#macro c_light_jade                     #c3fdb8
#macro c_tea_green                      #ccfb5d
#macro c_green_yellow                   #b1fb17
#macro c_slime_green                    #bce954
#macro c_goldenrod                      #edda74
#macro c_harvest_gold                   #ede275
#macro c_sun_yellow                     #ffe87c
#macro c_corn_yellow                    #fff380
#macro c_parchment                      #ffffc2
#macro c_cream                          #ffffcc
#macro c_lemon_chiffon                  #fff8c6
#macro c_cornsilk                       #fff8dc
#macro c_beige                          #f5f5dc
#macro c_blonde                         #fbf6d9
#macro c_antiquewhite                   #faebd7
#macro c_champagne                      #f7e7ce
#macro c_blanchedalmond                 #ffebcd
#macro c_vanilla                        #f3e5ab
#macro c_tan_brown                      #ece5b6
#macro c_peach                          #ffe5b4
#macro c_mustard                        #ffdb58
#macro c_rubber_ducky_yellow            #ffd801
#macro c_bright_gold                    #fdd017
#macro c_golden_brown                   #eac117
#macro c_macaroni_and_cheese            #f2bb66
#macro c_saffron                        #fbb917
#macro c_beer                           #fbb117
#macro c_cantaloupe                     #ffa62f
#macro c_bee_yellow                     #e9ab17
#macro c_brown_sugar                    #e2a76f
#macro c_burlywood                      #deb887
#macro c_deep_peach                     #ffcba4
#macro c_ginger_brown                   #c9be62
#macro c_school_bus_yellow              #e8a317
#macro c_sandy_brown                    #ee9a4d
#macro c_fall_leaf_brown                #c8b560
#macro c_orange_gold                    #d4a017
#macro c_sand                           #c2b280
#macro c_cookie_brown                   #c7a317
#macro c_caramel                        #c68e17
#macro c_brass                          #b5a642
#macro c_khaki                          #ada96e
#macro c_camel_brown                    #c19a6b
#macro c_bronze                         #cd7f32
#macro c_tiger_orange                   #c88141
#macro c_cinnamon                       #c58917
#macro c_bullet_shell                   #af9b60
#macro c_dark_goldenrod                 #af7817
#macro c_copper                         #b87333
#macro c_wood                           #966f33
#macro c_oak_brown                      #806517
#macro c_moccasin                       #827839
#macro c_army_brown                     #827b60
#macro c_sandstone                      #786d5f
#macro c_mocha                          #493d26
#macro c_taupe                          #483c32
#macro c_coffee                         #6f4e37
#macro c_brown_bear                     #835c3b
#macro c_red_dirt                       #7f5217
#macro c_sepia                          #7f462c
#macro c_orange_salmon                  #c47451
#macro c_rust                           #c36241
#macro c_red_fox                        #c35817
#macro c_chocolate                      #c85a17
#macro c_sedona                         #cc6600
#macro c_papaya_orange                  #e56717
#macro c_halloween_orange               #e66c2c
#macro c_pumpkin_orange                 #f87217
#macro c_construction_cone_orange       #f87431
#macro c_sunrise_orange                 #e67451
#macro c_mango_orange                   #ff8040
#macro c_dark_orange                    #f88017
#macro c_coral                          #ff7f50
#macro c_basket_ball_orange             #f88158
#macro c_light_salmon                   #f9966b
#macro c_tangerine                      #e78a61
#macro c_dark_salmon                    #e18b6b
#macro c_light_coral                    #e77471
#macro c_bean_red                       #f75d59
#macro c_valentine_red                  #e55451
#macro c_shocking_orange                #e55b3c
#macro c_scarlet                        #ff2400
#macro c_ruby_red                       #f62217
#macro c_ferrari_red                    #f70d1a
#macro c_fire_engine_red                #f62817
#macro c_lava_red                       #e42217
#macro c_love_red                       #e41b17
#macro c_grapefruit                     #dc381f
#macro c_chestnut_red                   #c34a2c
#macro c_cherry_red                     #c24641
#macro c_mahogany                       #c04000
#macro c_chilli_pepper                  #c11b17
#macro c_cranberry                      #9f000f
#macro c_red_wine                       #990012
#macro c_burgundy                       #8c001a
#macro c_chestnut                       #954535
#macro c_blood_red                      #7e3517
#macro c_sienna                         #8a4117
#macro c_sangria                        #7e3817
#macro c_firebrick                      #800517
#macro c_plum_pie                       #7d0541
#macro c_velvet_maroon                  #7e354d
#macro c_plum_velvet                    #7d0552
#macro c_rosy_finch                     #7f4e52
#macro c_puce                           #7f5a58
#macro c_dull_purple                    #7f525d
#macro c_rosy_brown                     #b38481
#macro c_khaki_rose                     #c5908e
#macro c_pink_bow                       #c48189
#macro c_lipstick_pink                  #c48793
#macro c_rose                           #e8adaa
#macro c_rose_gold                      #ecc5c0
#macro c_desert_sand                    #edc9af
#macro c_pig_pink                       #fdd7e4
#macro c_cotton_candy                   #fcdfff
#macro c_pink_bubble_gum                #ffdfdd
#macro c_misty_rose                     #fbbbb9
#macro c_pink                           #faafbe
#macro c_light_pink                     #faafba
#macro c_flamingo_pink                  #f9a7b0
#macro c_pink_rose                      #e7a1b0
#macro c_pink_daisy                     #e799a3
#macro c_cadillac_pink                  #e38aae
#macro c_carnation_pink                 #f778a1
#macro c_blush_red                      #e56e94
#macro c_hot_pink                       #f660ab
#macro c_watermelon_pink                #fc6c85
#macro c_violet_red                     #f6358a
#macro c_deep_pink                      #f52887
#macro c_pink_cupcake                   #e45e9d
#macro c_pink_lemonade                  #e4287c
#macro c_neon_pink                      #f535aa
#macro c_magenta                        #ff00ff
#macro c_dimorphotheca_magenta          #e3319d
#macro c_bright_neon_pink               #f433ff
#macro c_pale_violet_red                #d16587
#macro c_tulip_pink                     #c25a7c
#macro c_medium_violet_red              #ca226b
#macro c_rogue_pink                     #c12869
#macro c_burnt_pink                     #c12267
#macro c_bashful_pink                   #c25283
#macro c_dark_carnation_pink            #c12283
#macro c_plum                           #b93b8f
#macro c_viola_purple                   #7e587e
#macro c_purple_iris                    #571b7e
#macro c_plum_purple                    #583759
#macro c_indigo                         #4b0082
#macro c_purple_monster                 #461b7e
#macro c_purple_haze                    #4e387e
#macro c_eggplant                       #614051
#macro c_grape                          #5e5a80
#macro c_purple_jam                     #6a287e
#macro c_dark_orchid                    #7d1b7e
#macro c_purple_flower                  #a74ac7
#macro c_medium_orchid                  #b048b5
#macro c_purple_amethyst                #6c2dc7
#macro c_dark_violet                    #842dce
#macro c_violet                         #8d38c9
#macro c_purple_sage_bush               #7a5dc7
#macro c_lovely_purple                  #7f38ec
#macro c_aztech_purple                  #893bff
#macro c_medium_purple                  #8467d7
#macro c_jasmine_purple                 #a23bec
#macro c_purple_daffodil                #b041ff
#macro c_tyrian_purple                  #c45aec
#macro c_crocus_purple                  #9172ec
#macro c_purple_mimosa                  #9e7bff
#macro c_heliotrope_purple              #d462ff
#macro c_crimson                        #e238ec
#macro c_purple_dragon                  #c38ec7
#macro c_lilac                          #c8a2c8
#macro c_blush_pink                     #e6a9ec
#macro c_mauve                          #e0b0ff
#macro c_wisteria_purple                #c6aec7
#macro c_blossom_pink                   #f9b7ff
#macro c_thistle                        #d2b9d3
#macro c_periwinkle                     #e9cfec
#macro c_lavender_pinocchio             #ebdde2
#macro c_lavender_blue                  #e3e4fa
#macro c_pearl                          #fdeef4
#macro c_seashell                       #fff5ee
#macro c_milk_white                     #fefcff